[versions]
spotless = "8.7.0"
plugin-android = "9.2.1"
libxposed-api = "102.0.0"
hidden-api-bypass = "6.1"

[plugins]
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }

[libraries]
android-gradle = { module = "com.android.tools.build:gradle", version.ref = "plugin-android" }
libxposed-api = { module = "io.github.libxposed:api", version.ref = "libxposed-api" }
hidden-api-bypass = { module = "org.lsposed.hiddenapibypass:hiddenapibypass", version.ref = "hidden-api-bypass" }

[bundles]
